right_format = "$time $battery"

[character]
success_symbol = "[â†’](bold green)"
error_symbol = "[âœ•](bold red)"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "ğŸª«"
empty_symbol = "ğŸ’€"
format = "[$symbol $percentage ]($style)"
disabled = false

[[battery.display]]
threshold = 100
style = "bold red dimmed"

[time]
format = "[ğŸ•’ $time](bold red dimmed)"
time_format = "%T"
disabled = false

[shell]
fish_indicator = "ğŸŸ"
bash_indicator = "ğŸ§"
unknown_indicator = "mystery shell"
style = "cyan bold "
disabled = false